### ISSUE TITLE
Chain Rule audit Log MATCHED_VAR

### ISSUE THREAD

**Issue by Eyup-Devop** [corazawaf/coraza#978] opened 2024-02-03 16:15 UTC
## Description

When rule has "chain"  audit log MATCHED_VAR prints only last rule data

    "messages": [
        {
            "actionset": "",
            "message": "country",
            "data": {
                "file": "",
                "line": 1016,
                "id": 1001,
                "rev": "",
                "msg": "country",
                "data": "Matched Data: %REQUEST_URI: /wp-login.php", //this has to be country information.
                "severity": 6,
                "ver": "",
                "maturity": 0,
                "accuracy": 0,
                "tags": [],
                "raw": "SecRule GEO:COUNTRY_CODE \"@within GB,GR\" \"id:1001,phase:1,msg:'country',deny,severity:'INFO',status:403, logdata:'Matched Data: %%{MATCHED_VAR_NAME}: %{MATCHED_VAR}',chain\""
            }
        },
        {
            "actionset": "",
            "message": "deneme",
            "data": {
                "file": "",
                "line": 1016,
                "id": 1001,
                "rev": "",
                "msg": "deneme",
                "data": "Matched Data: %REQUEST_URI: /wp-login.php",
                "severity": 6,
                "ver": "",
                "maturity": 0,
                "accuracy": 0,
                "tags": [],
                "raw": "SecRule GEO:COUNTRY_CODE \"@within GB,GR\" \"id:1001,phase:1,msg:'country',deny,severity:'INFO',status:403, logdata:'Matched Data: %{MATCHED_VAR_NAME}: %{MATCHED_VAR}',chain\""
            }
        }
    ]

this is chain rule
first one check country code and in chain rule check request uri

**Comment by Eyup-Devop** [comment] 2024-02-06 12:39
No comment?

**Comment by fzipi** [comment] 2024-02-06 12:53
Yes. This is a comment.

**Comment by jptosso** [comment] 2024-02-06 13:44
this is actually fine, the problem is we should only log one of the chains. MATCHED_VAR is set when you finish a rule, that way the next chain will have access to it

**Comment by Eyup-Devop** [comment] 2024-02-06 19:35
Thanks. I decided to not to use matched vars. I use every rule parameters instead of matched vars

thank toy

**Comment by jcchavezs** [comment] 2024-02-19 16:05
Shall we close this?

**Comment by Eyup-Devop** [comment] 2024-02-19 16:54
of course we can close it.

thanks for your effort.

**Closed** 2024-02-19 16:54 UTC
Labels: bug
